# Generated by Django 3.2 on 2021-06-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20201109_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizform',
            name='questions',
            field=models.TextField(max_length=1000),
        ),
    ]
